// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc1-QhYClgiGSsHvO2J3a3TYKKaYpyWuM',
    appId: '1:973806653264:web:43fb75485781431ceae655',
    messagingSenderId: '973806653264',
    projectId: 'chat-app-edd29',
    authDomain: 'chat-app-edd29.firebaseapp.com',
    storageBucket: 'chat-app-edd29.firebasestorage.app',
    measurementId: 'G-FZR21FV690',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSC5CNfKIDO6SiealGeaI14FEOnaoBf9w',
    appId: '1:973806653264:android:5f4e22fe6dd20fbfeae655',
    messagingSenderId: '973806653264',
    projectId: 'chat-app-edd29',
    storageBucket: 'chat-app-edd29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAg3f4c-SnmcmsaO76k5XKC7uVdhfqhGE',
    appId: '1:973806653264:ios:886b8eda8b890279eae655',
    messagingSenderId: '973806653264',
    projectId: 'chat-app-edd29',
    storageBucket: 'chat-app-edd29.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAg3f4c-SnmcmsaO76k5XKC7uVdhfqhGE',
    appId: '1:973806653264:ios:886b8eda8b890279eae655',
    messagingSenderId: '973806653264',
    projectId: 'chat-app-edd29',
    storageBucket: 'chat-app-edd29.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc1-QhYClgiGSsHvO2J3a3TYKKaYpyWuM',
    appId: '1:973806653264:web:c34d821cab353cf7eae655',
    messagingSenderId: '973806653264',
    projectId: 'chat-app-edd29',
    authDomain: 'chat-app-edd29.firebaseapp.com',
    storageBucket: 'chat-app-edd29.firebasestorage.app',
    measurementId: 'G-1FLEPHWV01',
  );
}
